# Keywords configuration for job filtering and ranking

# Keywords to search for in job titles and descriptions
keywords:
  high_priority:
    - "SDET"
    - "Senior QA"
    - "QA Lead"
    - "Principal QA Engineer"
    - "Software QA Manager"
    - "QA Manager"
    - "Senior QA Engineer"
    - "QA Engineer"
    - "Automation Engineer"
    - "Engineering Lead"
    - "Tech Lead"

  medium_priority:
    - "Test Engineer"
    - "Automation Engineer"
    - "Quality Assurance"
    - "Software Tester"
    - "Dev Manager"
    - "Development Manager"
    - "Engineering Manager"
    - "Senior Engineering Manager"
    
  low_priority:
    - "Junior QA"
    - "Associate QA"
    - "QA Intern"
    - "Entry Level QA"

# Skills to boost ranking (QA and Engineering focused)
preferred_skills:
  - "Selenium"
  - "Cypress"
  - "Playwright"
  - "TestNG"
  - "JUnit"
  - "Appium"
  - "Postman"
  - "Jenkins"
  - "GitLab CI"
  - "Python"
  - "Java"
  - "JavaScript"
  - "TypeScript"
  - "React"
  - "Node.js"
  - "AWS"
  - "Kubernetes"
  - "Docker"
  - "PostgreSQL"
  - "MongoDB"
  - "Angular"
  - "Postgres"
  - "Mongo"
  - "Lambda"
  - "Serverless"
  - "Microservices"
  - "CI/CD"
  - "Agile"
  - "Scrum"
  - "Kanban"

# Locations preference (higher score for preferred locations)
preferred_locations:
  - "Remote"
  - "Pittsburgh"
  - "Greater Pittsburgh Area"
  

# Exclude jobs with these keywords
exclude_keywords:
  - "Clearance Required"
  - "Security Clearance"
  - "Top Secret"
